import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useRoles } from '@/contexts/RoleContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { CheckCircle2, XCircle, Loader2, Circle, FlaskConical, Info } from 'lucide-react';

type StepStatus = 'pending' | 'running' | 'pass' | 'fail' | 'skipped';

interface Step {
  key: string;
  label: string;
  status: StepStatus;
  message?: string;
  finishedAt?: string;
}

const INITIAL_STEPS: Step[] = [
  { key: 'submit', label: 'Submit a test request', status: 'pending' },
  { key: 'history', label: 'Appears in your request history', status: 'pending' },
  { key: 'admin', label: 'Visible to admins for review', status: 'pending' },
  { key: 'cleanup', label: 'Test request removed', status: 'pending' },
];

export function RoleRequestFlowTest() {
  const { user } = useAuth();
  const { isReviewer } = useRoles();
  const [steps, setSteps] = useState<Step[]>(INITIAL_STEPS);
  const [running, setRunning] = useState(false);
  const [hasRealPending, setHasRealPending] = useState<boolean | null>(null);
  const [summary, setSummary] = useState<string | null>(null);

  useEffect(() => {
    void checkExistingPending();
  }, [user?.id]);

  const checkExistingPending = async () => {
    if (!user?.id) return;
    const { data, error } = await supabase
      .from('role_requests')
      .select('id')
      .eq('user_id', user.id)
      .eq('status', 'pending')
      .limit(1);
    if (error) {
      setHasRealPending(false);
      return;
    }
    setHasRealPending((data?.length ?? 0) > 0);
  };

  const updateStep = (key: string, patch: Partial<Step>) => {
    setSteps(prev => prev.map(s => (s.key === key ? { ...s, ...patch, finishedAt: patch.status && patch.status !== 'running' ? new Date().toLocaleTimeString() : s.finishedAt } : s)));
  };

  const runTest = async () => {
    if (!user?.id) return;
    setRunning(true);
    setSummary(null);
    setSteps(INITIAL_STEPS.map(s => ({ ...s })));

    let insertedId: string | null = null;
    const failures: string[] = [];

    // Step 1 — submit
    updateStep('submit', { status: 'running' });
    if (isReviewer) {
      updateStep('submit', { status: 'skipped', message: 'You already have the reviewer role — skipping insert.' });
    } else {
      const { data, error } = await supabase
        .from('role_requests')
        .insert({
          user_id: user.id,
          requested_role: 'reviewer',
          justification: '[FLOW-TEST] Auto-generated by the role request flow test. Will be deleted automatically.',
          status: 'pending',
        })
        .select('id')
        .single();
      if (error || !data) {
        updateStep('submit', { status: 'fail', message: error?.message ?? 'Insert returned no row' });
        failures.push(`Submit: ${error?.message ?? 'no row returned'}`);
      } else {
        insertedId = data.id;
        updateStep('submit', { status: 'pass', message: `Test request created (id ${data.id.slice(0, 8)}…).` });
      }
    }

    // Step 2 — history read-back
    updateStep('history', { status: 'running' });
    if (!insertedId) {
      updateStep('history', { status: 'skipped', message: 'No test request was created — nothing to verify.' });
    } else {
      const start = Date.now();
      let found = false;
      let lastErr: string | undefined;
      while (Date.now() - start < 2000) {
        const { data, error } = await supabase
          .from('role_requests')
          .select('id, status, created_at')
          .eq('user_id', user.id)
          .eq('id', insertedId)
          .maybeSingle();
        if (error) {
          lastErr = error.message;
          break;
        }
        if (data) {
          found = true;
          break;
        }
        await new Promise(r => setTimeout(r, 300));
      }
      if (found) {
        updateStep('history', { status: 'pass', message: 'Request appears in your history.' });
      } else {
        updateStep('history', { status: 'fail', message: lastErr ?? 'Not found within 2s' });
        failures.push(`History: ${lastErr ?? 'not found'}`);
      }
    }

    // Step 3 — admin visibility (count via SECURITY DEFINER RPC, only ever returns own user count)
    updateStep('admin', { status: 'running' });
    if (!insertedId) {
      updateStep('admin', { status: 'skipped', message: 'No test request was created — nothing to verify.' });
    } else {
      const { data, error } = await supabase.rpc('count_pending_role_requests_for_user', { _user_id: user.id });
      if (error) {
        updateStep('admin', { status: 'fail', message: error.message });
        failures.push(`Admin visibility: ${error.message}`);
      } else if ((data ?? 0) >= 1) {
        updateStep('admin', { status: 'pass', message: `Confirmed: ${data} pending request${data === 1 ? '' : 's'} visible to admins.` });
      } else {
        updateStep('admin', { status: 'fail', message: `RPC returned ${data}` });
        failures.push(`Admin visibility: count was ${data}`);
      }
    }

    // Step 4 — cleanup (always runs if we created a row)
    updateStep('cleanup', { status: 'running' });
    if (!insertedId) {
      updateStep('cleanup', { status: 'skipped', message: 'Nothing to clean up.' });
    } else {
      const { error } = await supabase
        .from('role_requests')
        .delete()
        .eq('id', insertedId)
        .eq('user_id', user.id);
      if (error) {
        updateStep('cleanup', { status: 'fail', message: error.message });
        failures.push(`Cleanup: ${error.message}`);
      } else {
        updateStep('cleanup', { status: 'pass', message: 'Test request deleted.' });
      }
    }

    setSummary(failures.length === 0 ? 'All checks passed — the role request pipeline is healthy.' : `Issues found:\n${failures.map(f => `• ${f}`).join('\n')}`);
    setRunning(false);
    void checkExistingPending();
  };

  const renderIcon = (status: StepStatus) => {
    switch (status) {
      case 'running': return <Loader2 className="h-4 w-4 animate-spin text-primary" />;
      case 'pass': return <CheckCircle2 className="h-4 w-4 text-primary" />;
      case 'fail': return <XCircle className="h-4 w-4 text-destructive" />;
      case 'skipped': return <Info className="h-4 w-4 text-muted-foreground" />;
      default: return <Circle className="h-4 w-4 text-muted-foreground" />;
    }
  };

  const renderBadge = (status: StepStatus) => {
    const map: Record<StepStatus, { label: string; variant: any }> = {
      pending: { label: 'pending', variant: 'outline' },
      running: { label: 'running', variant: 'secondary' },
      pass: { label: 'pass', variant: 'default' },
      fail: { label: 'fail', variant: 'destructive' },
      skipped: { label: 'skipped', variant: 'outline' },
    };
    return <Badge variant={map[status].variant}>{map[status].label}</Badge>;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FlaskConical className="h-5 w-5" />
          Test the role request flow
        </CardTitle>
        <CardDescription>
          Verify end-to-end that submitting a role request works on your account. This creates a real
          request, confirms it shows up everywhere it should, then deletes it. No admin action required.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {hasRealPending && (
          <Alert>
            <Info className="h-4 w-4" />
            <AlertTitle>You already have a pending request</AlertTitle>
            <AlertDescription>
              Resolve or wait for your existing pending role request before running the test, so we don't
              touch your real submission.
            </AlertDescription>
          </Alert>
        )}

        <div className="space-y-2">
          {steps.map((step, i) => (
            <div key={step.key} className="flex items-start gap-3 rounded-md border p-3">
              <div className="mt-0.5">{renderIcon(step.status)}</div>
              <div className="flex-1 min-w-0">
                <div className="flex items-center justify-between gap-2">
                  <span className="text-sm font-medium">
                    {i + 1}. {step.label}
                  </span>
                  <div className="flex items-center gap-2 shrink-0">
                    {step.finishedAt && (
                      <span className="text-xs text-muted-foreground">{step.finishedAt}</span>
                    )}
                    {renderBadge(step.status)}
                  </div>
                </div>
                {step.message && (
                  <p className="mt-1 text-xs text-muted-foreground break-words">{step.message}</p>
                )}
              </div>
            </div>
          ))}
        </div>

        {summary && (
          <Alert variant={summary.startsWith('All checks') ? 'default' : 'destructive'}>
            <AlertTitle>{summary.startsWith('All checks') ? 'Test complete' : 'Test finished with issues'}</AlertTitle>
            <AlertDescription className="whitespace-pre-line">{summary}</AlertDescription>
          </Alert>
        )}

        <Button onClick={runTest} disabled={running || hasRealPending === true} className="w-full sm:w-auto">
          {running ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" /> Running…</> : 'Run test'}
        </Button>
      </CardContent>
    </Card>
  );
}

export default RoleRequestFlowTest;
