import { ProductDetails } from "@/types/productDetails";

export const SegProV3RT300: ProductDetails = {
  id: "everfortune-seg-pro-v3",
  name: "Seg Pro V3 (RT-300)",
  market: {
    onMarketSince: "2026",
    distributionChannels: ["Direct sales", "Partnerships"]
  },
  source: "FDA 510(k) database (K251306), CMUH Digital Imaging documentation, company announcement",
  company: "Ever Fortune AI",
  logoUrl: "/logos/ever-fortune.png",
  version: "3.0",
  website: "https://www.everfortuneai.com.tw/en/",
  category: "Auto-Contouring",
  evidence: [
    {
      link: "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfpmn/pmn.cfm?ID=K251306",
      type: "FDA 510(k) Database Entry",
      description: "FDA 510(k) device entry for Seg Pro V3 (K251306) - First radiotherapy software with PCCP"
    },
    {
      link: "https://www.cmuh.cmu.edu.tw/CMUHPagesSubDetail/Smart%20Healthcare/DigitalImaging_new/EFAI%20RT%20Suite%20CT%20HCAP-Segmentation%20System_en",
      type: "Clinical Implementation",
      description: "CMUH Digital Imaging - EFAI RT Suite implementation details and version updates"
    },
    {
      link: "https://pubmed.ncbi.nlm.nih.gov/36773828/",
      type: "Peer-reviewed Publication",
      description: "AI-assisted planning pipeline for hippocampal avoidance whole brain radiotherapy"
    },
    {
      link: "https://pubmed.ncbi.nlm.nih.gov/37585426/",
      type: "Peer-reviewed Publication",
      description: "Association of radiation dose to cardiac substructures with major ischaemic events following breast cancer radiotherapy"
    },
    {
      link: "https://www.everfortuneai.com.tw/en/",
      type: "Company Product Page",
      description: "Ever Fortune AI official website"
    }
  ],
  features: [
    "First radiotherapy software with FDA PCCP authorization",
    "Supports 182 organs across 4 anatomical regions",
    "Full CT and MRI imaging compatibility",
    "Adaptive AI with model re-training under predetermined protocols",
    "Significantly reduces contouring time",
    "DICOM input and DICOM-RTSTRUCT output"
  ],
  modality: ["CT", "MRI"],
  githubUrl: "https://github.com/DLinRT-eu/dlinrteu-website/tree/main/src/data/products/auto-contouring/everfortune.ts",
  companyUrl: "https://www.everfortuneai.com.tw/en/",
  guidelines: [
    {
      url: "https://www.aapm.org/pubs/reports/detail.asp?docid=171",
      name: "AAPM TG-263",
      version: "2018",
      reference: "Nomenclature standardization for structure names",
      compliance: "partial"
    }
  ],
  productUrl: "https://medical.everfortuneai.com.tw/products/efai-autoseg",
  regulatory: {
    ce: {
      type: "MDR",
      class: "IIa",
      status: "cleared",
      regulation: "MDR 2017/745"
    },
    fda: {
      type: "510(k) with PCCP",
      class: "Class II",
      notes: "First radiotherapy software (QKB) with Predetermined Change Control Plan (PCCP). PCCP allows model updates under predetermined protocols without regulatory re-submission.",
      status: "510k_cleared",
      productCode: "QKB",
      decisionDate: "2026-01-28",
      clearanceNumber: "K251306"
    },
    tfda: {
      notes: "Taiwan FDA clearance for global distribution",
      status: "Approved"
    },
    intendedUseStatement: "Seg Pro V3 is a software device intended to assist trained radiation oncology professionals, including, but not limited to, radiation oncologists, medical physicists, and dosimetrists, during their clinical workflows of radiation therapy treatment planning by providing initial contours of organs at risk on DICOM images. Seg Pro V3 is intended to be used on adult patients only. The contours are generated by deep-learning algorithms and then transferred to radiation therapy treatment planning systems. Seg Pro V3 must be used in conjunction with a DICOM-compliant treatment planning system to review and edit results generated. Seg Pro V3 is not intended to be used for decision making or to detect lesions. Seg Pro V3 is an adjunct tool and is not intended to replace a clinician's judgment and manual contouring of the normal organs on DICOM images. Clinicians must not use the software generated output alone without review as the primary interpretation. (Source: FDA 510(k) K251306 Summary, accessed 2026-05-30)"
  },
  technology: {
    deployment: ["On-premises", "Cloud-based"],
    integration: ["TPS integration"],
    processingTime: "Minutes per case",
    triggerForAnalysis: "Manual or automated"
  },
  description: "AI-powered multi-region auto-segmentation solution for radiation therapy planning. Version 3 of the RT Suite product line, now with expanded coverage across Head & Neck, Thorax, Abdomen, and Pelvis. First radiotherapy software (QKB) to receive FDA 510(k) clearance with a Predetermined Change Control Plan (PCCP), enabling adaptive AI model updates under predetermined protocols without regulatory re-submission.",
  keyFeatures: [
    "First radiotherapy software (QKB) with FDA Predetermined Change Control Plan (PCCP)",
    "182 organs across Head & Neck, Chest, Abdomen, and Pelvis",
    "Dual modality support: CT and MRI",
    "Adaptive AI - model updates without re-submission",
    "Fast auto-contouring workflow"
  ],
  lastRevised: "2026-05-30",
  lastUpdated: "2026-02-03",
  limitations: [
    "Assistive software only: outputs must be reviewed, edited, and approved by qualified clinicians before clinical use",
    "Intended for adult patients",
    "Performance may vary with imaging protocols and DICOM configurations",
    "102 structures verified from CMUH source; company claims 182 total - additional models may exist"
  ],
  releaseDate: "2026-01-28",
  certification: "CE & FDA",
  evidenceRigor: "E1",
  priorVersions: [
    {
      name: "RT Suite v1 (HCAP-Segmentation)",
      notes: "Original version with Head & Neck CT only. V3 expands to multi-region CT/MRI support with PCCP authorization.",
      productId: "everfortune-rt-suite",
      fdaClearance: "K220264"
    }
  ],
  subspeciality: "Radiation Oncology",
  clinicalImpact: "I2",
  diseaseTargeted: [
    "Head and Neck Cancer",
    "Thoracic Cancer",
    "Abdominal Cancer",
    "Pelvic Cancer"
  ],
  adoptionReadiness: "R3",
  anatomicalLocation: [
    "Head & Neck",
    "Thorax",
    "Abdomen",
    "Pelvis"
  ],
  evidenceRigorNotes: "Liu et al. 2023 hippocampal avoidance WBRT (pubmed/36773828). Cardiac substructures study (pubmed/37585426). Single-center studies on specific applications.",
  clinicalImpactNotes: "Single-center studies demonstrate clinical utility for specific applications (hippocampal avoidance, cardiac substructures).",
  evidenceMultiCenter: false,
  evidenceProspective: false,
  supportedStructures: [
    "Head-MR: Brainstem",
    "Head-MR: Eye L",
    "Head-MR: Eye R",
    "Head-MR: Hippocampus L",
    "Head-MR: Hippocampus R",
    "Head-MR: Lens L",
    "Head-MR: Lens R",
    "Head-MR: Optic Chiasm",
    "Head-MR: Optic Nerve L",
    "Head-MR: Optic Nerve R",
    "Head-MR: Pituitary",
    "Pelvis-MR: Bladder",
    "Pelvis-MR: Penile Bulb",
    "Pelvis-MR: Prostate",
    "Pelvis-MR: Rectum",
    "Pelvis-MR: Seminal Vesicles",
    "Chest-CT: Chest Wall",
    "Chest-CT: Chest Wall L",
    "Chest-CT: Chest Wall R",
    "Chest-CT: Lungs",
    "Chest-CT: Lung LLL",
    "Chest-CT: Lung LUL",
    "Chest-CT: Lung RLL",
    "Chest-CT: Lung RML",
    "Chest-CT: Lung RUL",
    "Chest-CT: Clavicle L",
    "Chest-CT: Clavicle R",
    "Chest-CT: Humerus L",
    "Chest-CT: Humerus R",
    "Chest-CT: Scapula L",
    "Chest-CT: Scapula R",
    "Chest-CT: Sternum",
    "Chest-CT: Ribs",
    "Chest-CT: Ribs L",
    "Chest-CT: Ribs R",
    "Chest-CT: Rib01 L",
    "Chest-CT: Rib02 L",
    "Chest-CT: Rib03 L",
    "Chest-CT: Rib04 L",
    "Chest-CT: Rib05 L",
    "Chest-CT: Rib06 L",
    "Chest-CT: Rib07 L",
    "Chest-CT: Rib08 L",
    "Chest-CT: Rib09 L",
    "Chest-CT: Rib10 L",
    "Chest-CT: Rib11 L",
    "Chest-CT: Rib12 L",
    "Chest-CT: Rib01 R",
    "Chest-CT: Rib02 R",
    "Chest-CT: Rib03 R",
    "Chest-CT: Rib04 R",
    "Chest-CT: Rib05 R",
    "Chest-CT: Rib06 R",
    "Chest-CT: Rib07 R",
    "Chest-CT: Rib08 R",
    "Chest-CT: Rib09 R",
    "Chest-CT: Rib10 R",
    "Chest-CT: Rib11 R",
    "Chest-CT: Rib12 R",
    "Chest-CT: VB T",
    "Chest-CT: VB T01",
    "Chest-CT: VB T02",
    "Chest-CT: VB T03",
    "Chest-CT: VB T04",
    "Chest-CT: VB T05",
    "Chest-CT: VB T06",
    "Chest-CT: VB T07",
    "Chest-CT: VB T08",
    "Chest-CT: VB T09",
    "Chest-CT: VB T10",
    "Chest-CT: VB T11",
    "Chest-CT: VB T12",
    "Abdomen-CT: Bowel",
    "Abdomen-CT: Bowel Large",
    "Abdomen-CT: Bowel Small",
    "Abdomen-CT: GI Tract",
    "Abdomen-CT: Adrenal L",
    "Abdomen-CT: Adrenal R",
    "Abdomen-CT: Gluteus",
    "Abdomen-CT: Gluteus Max L",
    "Abdomen-CT: Gluteus Max R",
    "Abdomen-CT: Gluteus Med L",
    "Abdomen-CT: Gluteus Med R",
    "Abdomen-CT: Gluteus Min L",
    "Abdomen-CT: Gluteus Min R",
    "Abdomen-CT: Iliopsoas L",
    "Abdomen-CT: Iliopsoas R",
    "Abdomen-CT: Bone Pelvic",
    "Abdomen-CT: Bone Pelvic L",
    "Abdomen-CT: Bone Pelvic R",
    "Abdomen-CT: Femur L",
    "Abdomen-CT: Femur R",
    "Abdomen-CT: Sacrum",
    "Abdomen-CT: VB L",
    "Abdomen-CT: VB L1",
    "Abdomen-CT: VB L2",
    "Abdomen-CT: VB L3",
    "Abdomen-CT: VB L4",
    "Abdomen-CT: VB L5",
    "Abdomen-CT: VB LS",
    "Abdomen-CT: VB S",
    "Abdomen-CT: VB S1"
  ],
  evidenceMultiNational: false,
  adoptionReadinessNotes: "Derived from E1 + CE + FDA 510(k): moderate implementation effort — local validation, interface testing and workflow confirmation required before adoption.",
  technicalSpecifications: {
    input: ["CT", "MRI"],
    output: ["Structure sets"],
    population: "Adult patients",
    inputFormat: ["DICOM"],
    outputFormat: ["DICOM-RTSTRUCT"]
  },
  evidenceVendorIndependent: false,
  evidenceExternalValidation: false
};
