
import { ProductDetails } from "@/types/productDetails";

export const HURA_IMAGING_PRODUCTS: ProductDetails[] = [
  {
    id: "hura-dvtarget",
    name: "DV.TARGET",
    company: "Hura Imaging",
    companyUrl: "https://huraimaging.com",
    productUrl: "http://www.huraimaging.com/dvtarget/",
    githubUrl: "https://github.com/DLinRT-eu/dlinrteu-website/tree/main/src/data/products/auto-contouring/hura-imaging.ts",
    description: "AI-powered auto-contouring solution for radiotherapy planning with advanced deep learning segmentation.",
    category: "Auto-Contouring",
    certification: "CE & FDA",
    logoUrl: "/logos/huraimaging.png",
    website: "http://www.huraimaging.com/dvtarget/",
    anatomicalLocation: ["Brain", "Head & Neck", "Thorax", "Breast", "Pelvis"],
    modality: ["CT", "MRI"],
    diseaseTargeted: ["Multiple Cancer Types"],
    keyFeatures: [
      "Fully automated organ and target volume segmentation",
      "Adaptive algorithms for challenging cases",
      "Seamless integration with treatment planning systems",
      "Rapid processing with high accuracy",
      "User-friendly interface with manual correction tools"
    ],
    supportedStructures: [
      "Brain: Brain",
      "Brain: Brainstem",
      "Brain: Eyes (L/R)",
      "Brain: Lens (L/R)",
      "Brain: Optic Chiasm",
      "Brain: Optic Nerve (L/R)",
      "Brain: Pituitary",
      
      "Head & Neck: Larynx",
      "Head & Neck: Mandible",
      "Head & Neck: Parotids (L/R)",
      "Head & Neck: Spinal Cord",
      "Head & Neck: Submandibular Glands (L/R)",
      
      "Thorax: Esophagus",
      "Thorax: Heart",
      "Thorax: Lungs (L/R)",
      "Thorax: Spinal Cord",
      
      "Breast: Breast (L/R)",
      "Breast: Heart",
      "Breast: Lungs (L/R)",
      
      "Pelvis: Bladder",
      "Pelvis: Femoral Heads (L/R)",
      "Pelvis: Prostate",
      "Pelvis: Rectum"
    ],
    technicalSpecifications: {
      population: "Adult patients",
      input: ["CT", "MRI"],
      inputFormat: ["DICOM"],
      output: ["Structure sets"],
      outputFormat: ["DICOM-RTSTRUCT"]
    },
    technology: {
      integration: ["PACS", "Treatment Planning Systems"],
      deployment: ["On-premises", "Cloud-based"],
      triggerForAnalysis: "Manual or automated workflow",
      processingTime: "Minutes per patient"
    },
    regulatory: {
      ce: {
        status: "Certified",
        class: "IIa",
        type: "MDR",
        regulation: "MDR 2017/745"
      },
      fda: {
        status: "510(k) Cleared",
        class: "Class II",
        type: "510(k)",
        clearanceNumber: "K202928",
        productCode: "QKB",
        regulationNumber: "21 CFR 892.2050",
        decisionDate: "2021-04-02",
        notes: "Cleared under company name DeepVoxel, Inc. (dba Hura Imaging)"
      },
      intendedUseStatement: "DV.Target is a software application that enables the routing of DICOM-compliant data (CT Images) to automatic image processing workflows, using machine learning-based algorithms to automatically delineate organs-at-risk (OARs). Contours generated by DV.Target may be used as an input to clinical workflows for treatment planning in radiation therapy."
    },
    market: {
      onMarketSince: "2020",
      distributionChannels: ["Direct sales", "Distribution partners"],
    },
    limitations: [
      "Only intended for normal organ contouring; not validated for tumor or clinical target volume (CTV) contouring",
      "FDA clearance is for CT images only; MRI use may not be FDA-cleared",
      "Contours are intended as input to clinical workflows and require physician review before use in treatment planning",
      "Performance may vary based on image quality and patient anatomy"
    ],
    version: "2.5",
    releaseDate: "2023-05-20",
    lastUpdated: "2024-01-15",
    lastRevised: "2026-01-26",
    source: "FDA 510(k) database (K202928), company official sources"
  }
];
