
import { ProductDetails } from "@/types/productDetails";

export const MIRADA_PRODUCTS: ProductDetails[] = [
  {
    id: "mirada-dlc",
    trainingData: {
        description: "Not publicly disclosed in the available documentation. The product utilizes deep learning algorithms for CT-based auto-contouring.",
        source: "FDA 510(k) summary K181572",
        sourceUrl: "https://www.accessdata.fda.gov/cdrh_docs/pdf18/K181572.pdf",
        disclosureLevel: "minimal"
    },
    evaluationData: {
        sourceUrl: "https://doi.org/10.3389/fonc.2023.1213068",
        description: "Multi-center comparison of 5 AI auto-contouring systems on 80 patients. The study demonstrated comparable contouring accuracy across systems.",
        primaryEndpoint: "Not specified",
        source: "Doolan et al. 2023 (DOI: 10.3389/fonc.2023.1213068)",
        results: "Demonstrated comparable contouring accuracy in a multi-center study.",
        studyDesign: "Retrospective multi-center comparison"
    },
    name: "DLC Expert",
    company: "Mirada Medical",
    companyUrl: "https://mirada-medical.com/radiation-oncology/",
    productUrl: "https://www.mirada-medical.com/radiation-oncology",
    githubUrl: "https://github.com/DLinRT-eu/dlinrteu-website/tree/main/src/data/products/auto-contouring/mirada.ts",
    description: "Deep learning-based auto-contouring software for radiation oncology providing consistent and rapid contouring of normal tissues.",
    category: "Auto-Contouring",
    structuresUnavailable: true,
    certification: "CE & FDA",
    logoUrl: "/logos/mirada-medical.png",
    website: "https://mirada-medical.com/product/mirada-dlcexpert-ai-autocontouring/",
    anatomicalLocation: ["Head & Neck", "Thorax", "Abdomen", "Pelvis"],
    modality: ["CT"],
    subspeciality: "Radiation Oncology",
    diseaseTargeted: ["Multiple Cancer Types"],
    keyFeatures: ["Deep learning algorithms", "Batch processing", "Clinical workflow integration"],
    technicalSpecifications: {
      population: "Adult patients",
      input: ["CT"],
      inputFormat: ["DICOM"],
      output: ["Structure sets"],
      outputFormat: ["DICOM-RTSTRUCT"]
    },
    technology: {
      integration: ["TPS integration", "PACS integration", "Workflow manager"],
      deployment: ["On-premises", "Cloud-based"],
      triggerForAnalysis: "Automatic or manual",
      processingTime: "Minutes per patient"
    },
    regulatory: {
      ce: {
        status: "withdrawn",
        class: "Class IIa",
        type: "MDD",
        regulation: "MDD 93/42/EEC"
      },
      fda: {
        status: "withdrawn",
        class: "Class II",
        type: "510(k)",
        clearanceNumber: "K181572",
        productCode: "QKB",
        regulationNumber: "21 CFR 892.2050",
        decisionDate: "2018-07-10",
        notes: "Cleared as 'Workflow Box' (includes DLCExpert). First FDA-cleared AI auto-contouring for radiation oncology."
      },
      intendedUseStatement: "Workflow Box is a software system designed to allow users to route DICOM-compliant data to and from automated processing components. Supported modalities include CT, MR, RTSTRUCT. Workflow Box includes processing components for automatically contouring imaging data using deformable image registration to support atlas based contouring, re-contouring of the same patient and machine learning based contouring. Workflow Box is a data routing and image processing tool which automatically applies contours to data which is sent to one or more of the included image processing workflows. Contours generated by Workflow Box may be used as an input to clinical workflows including, but not limited to, radiation therapy treatment planning. Workflow Box must be used in conjunction with appropriate software to review and edit results generated automatically by Workflow Box components, for example image visualization software must be used to facilitate the review and edit of contours generated by Workflow Box component applications. Workflow Box is intended to be used by trained medical professionals. (Source: FDA 510(k) K181572 Summary [Workflow Box, which includes DLCExpert], accessed 2026-05-30)"
    },
    market: {
      onMarketSince: "2019",
      distributionChannels: ["Discontinued - no longer actively marketed"]
    },
    evidenceRigor: "E2",
    clinicalImpact: "I2",
    evidenceRigorNotes: "Multiple independent peer-reviewed multi-institutional studies (Brouwer 2020, Choi 2020, Zhu 2021, Doolan 2023) confirm E2.",
    clinicalImpactNotes: "Multi-center study demonstrated comparable contouring accuracy. Product now discontinued.",
    adoptionReadiness: "R3",
    adoptionReadinessNotes: "Derived from E2 + CE + FDA 510(k): moderate implementation effort — local validation, interface testing and workflow confirmation required before adoption.",
    evidenceVendorIndependent: true,
    evidenceMultiCenter: true,
    evidenceMultiNational: false,
    evidenceProspective: false,
    evidenceExternalValidation: true,
    evidence: [
      {
        type: "Multi-vendor Comparative Study",
        description: "Doolan et al. Clinical evaluation of 5 commercial AI contouring systems (Mirada [Mir], MVision, Radformation, RayStation, TheraPanacea) on 80 patients (breast/H&N/lung/prostate). Mirada explicitly included and benchmarked — direct evidence for this product. Front Oncol 2023;13:1213068.",
        link: "https://doi.org/10.3389/fonc.2023.1213068"
      }
    ],
    version: "2.2",
    releaseDate: "2023-05-20",
    lastUpdated: "2026-06-15",
    keyPapers: [
    {"doi":"10.1016/j.radonc.2020.05.028","title":"Independent evaluation of DLCExpert for H&N contouring","authors":"Brouwer CL et al.","journal":"Radiother Oncol","year":"2020"},
    {"doi":"10.1016/j.radonc.2020.04.013","title":"Automated liver segmentation using Mirada DLC","authors":"Choi Y et al.","journal":"Radiother Oncol","year":"2020"},
    {"doi":"10.1080/0284186X.2021.1892183","title":"Multi-vendor DL auto-segmentation comparison","authors":"Zhu J et al.","journal":"Acta Oncol","year":"2021"},
    {"doi":"10.3389/fonc.2023.1104149","title":"Benchmarking commercial DL auto-contouring","authors":"Doolan P et al.","journal":"Front Oncol","year":"2023"}
  ],
    lastRevised: "2026-07-15",
    source: "Historical records - product discontinued; citation re-verified 2026-06-15 (Doolan 2023 directly evaluates Mirada per its Methods)."
  }
];
