import { ProductDetails } from "@/types/productDetails";

export const QOCAimageSmartRTContouringSystem: ProductDetails = {
  id: "quanta-qoca-image-smart-rt",
  name: "QOCA® image Smart RT Contouring System",
  market: {
    onMarketSince: "2024",
    distributionChannels: ["Direct sales"]
  },
  source: "FDA 510(k) database K231855, Quanta Computer corporate website; releaseDate proxied from FDA decision date (2024-02-13)",
  anatomy: ["pelvis", "head and neck"],
  company: "Quanta Computer Inc.",
  logoUrl: "/logos/quanta-computer.png",
  version: "ZSWR901",
  website: "https://www.qoca.net/",
  category: "Auto-Contouring",
  evidence: [
    {
      link: "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfPMN/pmn.cfm?ID=K231855",
      type: "Internal Validation",
      level: "1t",
      description: "K231855 — QOCA® image Smart RT Contouring System, cleared 2024-02-13"
    }
  ],
  features: [
    "Deep learning-based organ-at-risk segmentation",
    "Planning CT input",
    "DICOM-RTSTRUCT output for downstream TPS"
  ],
  modality: ["CT"],
  githubUrl: "https://github.com/DLinRT-eu/dlinrteu-website/tree/main/src/data/products/auto-contouring/quanta-computer.ts",
  companyUrl: "https://www.quantatw.com/quanta/english/default.aspx",
  productUrl: "https://www.qoca.net/",
  regulatory: {
    ce: {
      notes: "CE status not publicly confirmed at time of inclusion",
      status: "Not Available"
    },
    fda: {
      type: "510(k)",
      class: "II",
      notes: "Indicated for automatic OAR contouring on CT scans to support radiation therapy planning.",
      status: "Cleared",
      productCode: "QKB",
      decisionDate: "2024-02-13",
      clearanceNumber: "K231855",
      regulationNumber: "21 CFR 892.2050"
    },
    tga: {
      status: "Not Available"
    },
    intendedUseStatement: "Post-processing software for automatic delineation of organs at risk on CT scans, intended to assist radiation oncology clinicians in treatment planning."
  },
  technology: {
    deployment: ["On-premises"],
    integration: ["TPS via DICOM-RTSTRUCT"],
    processingTime: "Minutes per case",
    triggerForAnalysis: "Manual or workflow-driven on planning CT"
  },
  description: "AI-powered post-processing software that automatically delineates organs at risk on planning CT scans for radiation therapy. Designed to reduce contouring time and inter-observer variability in radiation oncology workflows.",
  keyFeatures: [
    "Automatic OAR contouring on CT for radiotherapy planning",
    "Deep learning segmentation models",
    "DICOM-RTSTRUCT export"
  ],
  lastRevised: "2026-06-01",
  lastUpdated: "2026-06-01",
  limitations: [
    "System must be used in conjunction with appropriate software such as Treatment Planning Systems and Interactive Contouring applications, to review, edit, and accept contours generated by the contouring system.",
    "The system does not provide a user interface for data visualization.",
    "System settings, user settings, progress status, and other functionalities are managed via a web-based interface.",
    "The software is not intended to automatically detect or contour lesions.",
    "Only DICOM images of adult patients are considered to be valid input."
  ],
  releaseDate: "2024-02-13",
  trainingData: {
    datasetSize: "Not publicly disclosed",
    demographics: "Not publicly disclosed",
    scannerModels: ["Not publicly disclosed"],
    datasetSources: ["Not publicly disclosed"],
    disclosureLevel: "minimal"
  },
  certification: "FDA",
  evidenceRigor: "E0",
  subspeciality: "Radiation Oncology",
  clinicalImpact: "I1",
  evaluationData: {
    source: "FDA 510(k) K231855",
    results: "Not publicly disclosed",
    sourceUrl: "https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfPMN/pmn.cfm?ID=K231855",
    description: "FDA 510(k) software verification and validation; specifics not publicly available.",
    studyDesign: "Software V&V",
    primaryEndpoint: "Not publicly disclosed"
  },
  diseaseTargeted: ["Multiple Cancer Types"],
  adoptionReadiness: "R3",
  compatibleSystems: [
    "Windows",
    "No specific requirement for the scanner model, it is recommended to use multi-detector CT (MDCT) equipment with more than 16 slices for Radiation Therapy Simulation CT, and DICOM compliance required.",
    "No Limitation on TPS model, DICOM compliance required."
  ],
  anatomicalLocation: [
    "Head & Neck",
    "Thorax",
    "Abdomen",
    "Pelvis"
  ],
  evidenceRigorNotes: "FDA 510(k) software verification and validation. Limited public peer-reviewed clinical evidence at time of inclusion.",
  clinicalImpactNotes: "Automated OAR contouring; awaiting independent multi-center clinical validation.",
  evidenceMultiCenter: false,
  evidenceProspective: false,
  supportedStructures: [
    "Head & Neck: brain stem",
    "Head & Neck: Mandible",
    "Head & Neck: Pharyngeal Constrictor Muscle",
    "Head & Neck: Spinal cord",
    "Head & Neck: Thyroid",
    "Head & Neck: Eye R",
    "Head & Neck: Eye L",
    "Head & Neck: Lens R",
    "Head & Neck: Lens L",
    "Head & Neck: Optic Nerve L",
    "Head & Neck: Optic Nerve R",
    "Head & Neck: Parotid L",
    "Head & Neck: Parotid R",
    "Head & Neck: Esophagus",
    "Pelvis: Anorectum",
    "Pelvis: Bladder",
    "Pelvis: Bowel bag",
    "Pelvis: Lumbar spine L5",
    "Pelvis: Bilateral seminal vesicles",
    "Pelvis: Iliac R",
    "Pelvis: Proximal femur L",
    "Pelvis: Proximal femur R",
    "Pelvis: Iliac L"
  ],
  evidenceMultiNational: false,
  structuresUnavailable: true,
  adoptionReadinessNotes: "Derived from E1 + FDA 510(k): moderate implementation effort — local validation, interface testing and workflow confirmation required before adoption.",
  technicalSpecifications: {
    input: ["CT"],
    output: ["Structure sets"],
    population: "Adult patients",
    inputFormat: ["DICOM"],
    outputFormat: ["DICOM-RTSTRUCT"]
  },
  evidenceVendorIndependent: false,
  evidenceExternalValidation: false
};
