import { ProductDetails } from "@/types/productDetails";

export const Verify: ProductDetails = {
  id: "mvision-verify",
  name: "Verify",
  market: {
    onMarketSince: "2020",
    distributionChannels: ["Direct sales", "Distribution partners"]
  },
  source: "MVision AI official website, regulatory classification based on product function",
  usesAI: false,
  company: "MVision AI",
  logoUrl: "/logos/mvision-ai.png",
  version: "2.1",
  website: "https://mvision.ai/verify/",
  category: "Performance Monitor",
  features: [
    "Contour comparison",
    "Visualization tools",
    "AI contour analysis",
    "Clinical workflow integration"
  ],
  modality: "RT Struct",
  githubUrl: "https://github.com/DLinRT-eu/dlinrteu-website/tree/main/src/data/products/performance-monitor/mvision.ts",
  companyUrl: "https://www.mvision.ai/",
  productUrl: "https://mvision.ai/verify/",
  regulatory: {
    ce: {
      type: "Software Tool",
      class: "N/A",
      notes: "Visualization and comparison tool - not a diagnostic device",
      status: "not_applicable"
    },
    fda: {
      class: "N/A",
      notes: "Non-diagnostic visualization tool for comparing contours. Does not make clinical decisions.",
      status: "not_applicable"
    },
    intendedUseStatement: "\"Verify helps clinicians compare and visualize user and AI-generated contours, facilitating informed contouring decisions based on clear, quantifiable data. Clinicians can easily compare contours generated by users or AI against selected reference structures and calculate essential comparison metrics including the Dice score and Hausdorff distance.\" Not intended for diagnostic use; MDR exempt visualization/QA tool. (Source: MVision AI official product page https://mvision.ai/verify/, accessed 2026-05-30)"
  },
  technology: {
    deployment: ["Cloud-based", "On-premises"],
    integration: ["TPS integration", "PACS integration", "LINAC connectivity"],
    processingTime: "Minutes per patient",
    triggerForAnalysis: "Automatic after treatment delivery"
  },
  description: "Contour comparison tool for visualizing and comparing user-generated and AI-generated contours. Note: This is a QA/visualization tool for monitoring AI contour quality—it may or may not use AI itself.",
  keyFeatures: [
    "Contour visualization",
    "AI vs manual comparison",
    "Interactive analysis tools",
    "Clinical decision support",
    "Workflow integration"
  ],
  lastRevised: "2026-05-30",
  lastUpdated: "2026-02-23",
  releaseDate: "2023-08-15",
  certification: "MDR Exempt",
  evidenceRigor: "E0",
  subspeciality: "Medical Physics",
  clinicalImpact: "I1",
  diseaseTargeted: ["Cancer"],
  adoptionReadiness: "R1",
  anatomicalLocation: ["Multiple"],
  evidenceRigorNotes: "QA visualization tool. No peer-reviewed publications. MDR exempt.",
  monitorsAIProducts: ["Auto-Contouring outputs"],
  clinicalImpactNotes: "QA/monitoring tool for comparing AI-generated and manual contours.",
  adoptionReadinessNotes: "Derived from E0 + no public regulatory clearance: major assurance burden — sparse peer-reviewed evidence and/or no public clearance; not adoption-ready, generate evidence first.",
  technicalSpecifications: {
    input: ["AI contours", "Manual contours", "Structure sets"],
    output: ["Comparison reports", "Visualization data"],
    population: "Radiotherapy patients with contoured structures",
    inputFormat: ["DICOM-RTSTRUCT", "RT Structure Sets"],
    outputFormat: ["PDF", "Interactive dashboard"]
  }
};
