-- Bulk import newsletter subscribers from CSV files
-- Only importing SUBSCRIBED status entries with deduplication

INSERT INTO public.newsletter_subscribers (email, first_name, last_name, consent_given, created_at)
VALUES
  -- From File 1 (noreply@dlinrt.eu-2.csv) - SUBSCRIBED only
  ('naaman@bitfount.com', '', '', true, now()),
  ('dhananjay.eu@gmail.com', '', '', true, now()),
  ('sara@ai-medical.ch', '', '', true, now()),
  ('jkvaikkattil@gmail.com', '', '', true, now()),
  ('r.spijkerman-7@prinsesmaximacentrum.nl', '', '', true, now()),
  ('zhangye615@gmail.com', '', '', true, now()),
  ('jenny.gorgisyan@skane.se', '', '', true, now()),
  ('mustafa.i.kadhim@skane.se', '', '', true, now()),
  ('tessa.leer@gmail.com', '', '', true, now()),
  ('p.m.a.van.ooijen@umcg.nl', '', '', true, now()),
  ('patrick.hylkema@radicare.eu', '', '', true, now()),
  ('b.schipaanboord@nki.nl', '', '', true, now()),
  ('n.m.sijtsema@umcg.nl', '', '', true, now()),
  ('matteo.maspero.it@gmail.com', '', '', true, now()),
  ('shayori.555@gmail.com', '', '', true, now()),
  ('f.j.w.m.dankers@lumc.nl', '', '', true, now()),
  ('lakshmikrishnan012001@gmail.com', '', '', true, now()),
  ('usman.lula@uhb.nhs.uk', '', '', true, now()),
  ('frank.emert@psi.ch', '', '', true, now()),
  ('bigbang966@gmail.com', '', '', true, now()),
  ('brent.vanderheyden@ugent.be', '', '', true, now()),
  ('ada6225max@yahoo.com.tw', '', '', true, now()),
  ('dylan.callens@uzleuven.be', '', '', true, now()),
  ('t.s.leijstra@isala.nl', '', '', true, now()),
  
  -- From File 2 (Mailchimp export) - SUBSCRIBED and webinar registrants with names
  ('belardo.alfonso@hsr.it', 'Alfonso', 'Belardo', true, now()),
  ('g.f.perotti.bernardini@gmail.com', 'Giuliano', 'Perotti Bernardini', true, now()),
  ('m.a.stryja@tudelft.nl', 'Mikołaj', 'Stryja', true, now()),
  ('info@dosimetrica.com', 'Nicola', 'Franza', true, now()),
  ('osimshemanto0@gmail.com', 'Mohammad Ullah', 'Shemanto', true, now()),
  ('amsz966@gmail.com', 'Ali', 'Zaila', true, now()),
  ('j.k.veldman@amsterdamumc.nl', 'Jeffrey', 'Veldman', true, now()),
  ('grujicmilos10@gmail.com', 'Milos', 'Grujic', true, now()),
  ('J.penninkhof@erasmusmc.nl', 'J.', 'Penninkhof', true, now()),
  ('a.minken@radiotherapiegroep.nl', 'Andre', 'Minken', true, now()),
  ('sopokhundadze@gmail.com', 'Sophio', '', true, now()),
  ('r.kierkels@radiotherapiegroep.nl', 'Roel', 'Kierkels', true, now()),
  ('g.h.bol@umcutrecht.nl', 'Gijs', 'Bol', true, now()),
  ('j.kleijnen@haaglandenmc.nl', 'Jean-Paul', 'Kleijnen', true, now()),
  ('cbhalke14@gmail.com', 'Chaitanya', '', true, now()),
  ('r.simoes@nki.nl', 'Rita', 'Simões', true, now()),
  ('KrishnaJeanne.GodinoPadre@ukdd.de', 'Krishna', 'Godino Padre', true, now()),
  ('Sai.Kumar.Samala@uth.tmc.edu', 'Sai Kumar', 'Samala', true, now()),
  ('norina.predescu@mvision.ai', 'Norina', 'Predescu', true, now()),
  ('adnanjafar1433@gmail.com', 'Adnan', '', true, now()),
  ('rajesh.thiyagarajan@ihhhealthcare.com', 'Rajesh', 'T', true, now()),
  ('Physiker@ik.me', 'Mauricio', 'Leick', true, now()),
  ('a.petoukhova@haaglandenmc.nl', 'Anna', 'Petoukhova', true, now()),
  ('banu_ozan@hotmail.com', 'Hamdiye', 'Ozan', true, now()),
  ('dechambre.d@gmail.com', 'Dechambre', '', true, now()),
  ('stefania.volpe@ieo.it', 'Stefania', 'Volpe', true, now()),
  ('mo1310@gmail.com', 'Mohammad', 'Hussien', true, now()),
  ('e.slooten@nwz.nl', 'Erik', 'Slooten', true, now()),
  ('j.j.w.lagendijk@umcutrecht.nl', 'Jan', 'Lagendijk', true, now()),
  ('mohamed.shelan@insel.ch', 'Mo', 'Shelan', true, now()),
  ('lukas.a.zimmermann@meduniwien.ac.at', 'Lukas', 'Zimmermann', true, now()),
  ('n.krah@hollandptc.nl', 'Nils', 'Krah', true, now()),
  ('hans.ligtenberg@mst.nl', 'Hans', 'Ligtenberg', true, now()),
  ('giorgia.meschini@gehealthcare.com', 'Giorgia', 'Meschini', true, now()),
  ('info@dlinrt.eu', 'DLinRT', 'EU', true, now()),
  ('themedicalphysicist@gmail.com', 'Rajesh', 'Thiyagarajan', true, now()),
  ('a.koops01@umcg.nl', 'Annamieke', '', true, now()),
  ('ilaria.rinaldi@maastro.nl', 'Ilaria', 'Rinaldi', true, now()),
  ('bryanthebeemang@gmail.com', 'Bryan', 'Thebeemang', true, now()),
  ('bosch.v.d.m@bvi.nl', 'Michiel', 'van den Bosch', true, now()),
  ('essers.m@bvi.nl', 'Marion', 'Essers', true, now()),
  ('e.m.kerkhof@lumc.nl', 'Ellen', 'Kerkhof', true, now()),
  ('d.rodriguezgarcia@hubruxelles.be', 'Diana', 'Rodriguez', true, now()),
  ('sa.vd.velden@nki.nl', 'Sandra', 'van der Velden', true, now()),
  ('hossein.jafarzadeh@mail.mcgill.ca', 'Hossein', '', true, now()),
  ('e.seravalli@umcutrecht.nl', 'Enrica', 'Seravalli', true, now()),
  ('rbtino@mdanderson.org', 'Rance', '', true, now()),
  ('estelle.loyen@uclouvain.be', 'Estelle', '', true, now())
ON CONFLICT (email) DO UPDATE SET
  first_name = CASE WHEN EXCLUDED.first_name != '' AND newsletter_subscribers.first_name = '' THEN EXCLUDED.first_name ELSE newsletter_subscribers.first_name END,
  last_name = CASE WHEN EXCLUDED.last_name != '' AND newsletter_subscribers.last_name = '' THEN EXCLUDED.last_name ELSE newsletter_subscribers.last_name END,
  updated_at = now();